backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "assets/images"
public_folder: "images"

collections:
  - name: "blog" 
    label: "Blog" 
    folder: "_posts" 
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post-right-sidebar"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Categories", name: "Categories", widget: "string"}
      - {label: "image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Articles" 
    label: "Articles" 
    folder: "_fyd" 
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post-right-sidebar"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Categories", name: "Categories", widget: "string"}
      - {label: "image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}